image: cirrusci/flutter:stable

stages:
  - archive

android:release:
  stage: archive
  before_script:
    - flutter create .
    - flutter packages get
    - flutter clean
  script:
    - flutter doctor --android-licenses
    - flutter build apk --release
  artifacts:
    paths:
      - "**/**/**/**/**/**/*.apk"
    expire_in: 1 day

web:release:
  stage: archive
  before_script:
    - flutter create .
    - flutter packages get
    - flutter clean
  script:
    - flutter build web --release